#+title:      verse 48
#+date:       [2025-03-31 Mon 06:55]
#+filetags:   
#+identifier: 20250331T065527

* Verse

योगस्थ: कुरु कर्माणि सङ्गं त्यक्त्वा धनञ्जय |
सिद्ध्यसिद्ध्यो: समो भूत्वा समत्वं योग उच्यते || 48||

* Notes

Steadfast in devotion do thy works, O Dhanamjaya, casting off
attachment, being the same in success and failure. Evenness is called
Yoga.

** My notes

Do work being established in Yoga. Here work refers to day-to-day
dutyful work. Yoga refers to Karma Yoga, a one pointed conviction that
the current duties are set into motion by karma and by prforming them
without attachment to results will lead to purity of mind.

When working do not think about the resutls. Perform the means with
heart. Even the spiritual results are of no concern. They will come
when the means are perfected. Be free from elation and depressin, be
even. This evenness is Yoga (Karma Yoga).


- Even tho, we do not do them for result, all work should be done with
  upbeat attitude and care.
  
- I am not mentioning God here to make the verse stand on its
  own. But, commenters have included god. The gist is, perofrm work
  with a one pointed conviciton that you are doing Gods work with
  support from God. We will perform some of his work for a time. When
  we are ready, with his grace, he will free us from samsara.

  - Support of God: I am doing work not with the help of other people
    or money or health or my education. All of those are there, but my
    real support is God

