* Verse

कर्मण्येवाधिकारस्ते मा फलेषु कदाचन |
मा कर्मफलहेतुर्भूर्मा ते सङ्गोऽस्त्वकर्मणि || 47 ||

* Notes

The following verse is very important and requires a separate notes. In this verse
Swami Saravapriyananda makes ten key observations,

1. Karma and Phalam (Action and Result)

   - Actions (karma) --> Results (Phalam).
   - Phalam means fruit. Here it means fuits of work.
   - We have the possibility of controling our actions, but not the results.
     
2. Free Will

   - For this phylosophy to work, it is assumed that we have free will.
   - The final teaching of advaita vedanta is that this is all will of
     god, and, you are god. But until this big realization, for all
     practical purposes we should assume we have free will.
     
3. Importance of Focus

   - The verse uses work in singular sense.
   - This emphasis may be related to the fact that Krishna recommends
     doing one work at a time. This allows us to do a conscious and
     attentive effort.
     
4. Three Approaches to Action
   
   1. Tamasik: Giving up on work. Inaction.
   2. Rajasik: How majority of worldy success happens. Action prompted
      thorugh self interest.
   3. Sattvik: Work prompted with a clean and clear mind. Work for
      greater good. Since there is no personal gain in this type of
      work, there will be calmness and peace. But, remember this is
      also not Karma Yoga. Karma Yoga goes beyond this.

5. Karma yoga is beyond these 3 approaches. $3 > 2 > 1$. It
   disinterested action.
      
6. Disinterested vs. Uninterested Action

   - Disinterested: Doing work but not really into it. Having no focus
     or enthusiasm.
   - Uninterested: Work with enthusiam, give your 100% to task at
     hand. Once done, do not worry about the result. Phalam is not in
     our hands.
     
7. How to Spiritualize Action and Results

   - Action: Do action as an offering to God or as self purification.
   - Result: Accept highs and lows with dignitiy. Surrender the
     results to god and always remember the goal is beyond the
     worldly.
     
8. Not Claiming the Results

   - By claiming results we fuel doership (kartritva), this binds us to samsara.
     
9. How to Reduce Desires

   When a desire bubbles in the mind, try to remember the following,
   
   - Desire stems from a sense of incompleteness. The incompleteness
     we feel is due to us not realizing we are inherently complete, but
     we are ignorant of it.
   - Desire makes us dependent (we become slaves). The more we are
     slaves to our desires, the more we stride away from freedom.
   - Unfulfilled desires lead to frustration.
   - Desires never end. Fulfilling one will just lead to another.
     
10. Karma and its Results are Impermanent

    - The Self is eternal. It cannot be tied down to temporary agency like work and results.
    - Work cannot untimately free us. Work done through Karma Yoga
      leads to purity, and a path to Self knowledge (Jnana).
      
11. Do Not Give in to Inaction

    - Laziness and escapism is much worse than desirous work.
    - If you cannot immediately perform disinterested action (its
      quite hard), work with selfish motives (but keep pushing the
      motives to be more sattvik).
    - The more sattvic ones motives are the more easy to transition to
      Karma Yoga.
