#+title:      hotel style tiffin sambar
#+date:       [2026-02-21 Sat 16:58]
#+filetags:   :vismaifood:
#+identifier: 20260221T165827

* Hotel style tiffin sambar

Three main steps,

1. Pressure cook lentil (dal)
2. Make sambar paste
3. Cook sambar

** Pressure cook lentil

Cook for 17 minutes in instant pot and make a fine paste after cooling.

- 30 minute soaked 1/2 cup toor dal
- 1/2 tea spoon red chilli powder
- 1/4 tea spoon turmeric
- 1 small onion cut. If it is Jumbo onion, 1/4th.
- 1 drum stick. 1 inch cuts, split them and also skin.
- 1/4 cup bottle gourd
- 1/3 cup skinned sweet pumpkin
- 2 split green chilli
- 1 tomato cut.
- 1/4th cup carrot cut.
- 600 ml water.

** Sambar paste

Dry roast the following on light flame until fragrant. After the dal
cook for 1/2 the time add 1/3rd cup fresh coconut. After cooling
make it a fine paste.

- 3 medium hot red chilli
- 1 table spoon chana dal
- 2 table spoon coriander seeds.
- 1/8th tea spoon methi seeds.
- 1/2 tea spoon cumin seeds
- 1 table spoon urud dal
- t table spoon rice.
- 

** Cook sambar

Add 2 table spoon oil and add 1 tea spoon mustard, let them splatter.
Add 1/2 tea spoon cumin seeds and add 1/2 dry red chilli split. Add
two stems of curry leaves. Add tamarind paste and let it boil once. Add
the sambar paste and boil once. Add the dal paste and let it cook for 2 min.
Add 1.75 liters of water and let it simmer on medium flame for 20 minutes.
Add chopped coriander and 1.5 table spoon ghee. Let it boil for 25 minutes
more.

- Tamrind paste: 40g 300 ml water.
