#+title:      amazon leadership principles
#+date:       [2025-05-08 Thu 20:28]
#+filetags:   
#+identifier: 20250508T202830
#+STARTUP: indent

* Amazon leadership principles

** 1. Customer obsession

#+begin_quote
Leaders start with the customer and work backwards. They work
vigorously to earn and keep customer trust. Although leaders pay
attention to competitors, they obsess over customers.
#+end_quote

*Possible questions:*

- Tell me about a time you have to deal with a very difficult customer.
- Describe a situation where you negotiated a win-win.
  
** 2. Ownership

#+begin_quote
Leaders are owners. They think long term and don’t sacrifice long-term
value for short-term results. They act on behalf of the entire
company, beyond just their own team. They never say “that’s not my
job.”
#+end_quote

*Possible questions*

- Describe a tough situation where you had to step into a leadership role.
- Tell me about a tough decision you made during a project.
  
** 3. Invent and Simplify

#+begin_quote
Leaders expect and require innovation and invention from their teams
and always find ways to simplify. They are externally aware, look for
new ideas from everywhere, and are not limited by “not invented here.”
As we do new things, we accept that we may be misunderstood for long
periods of time.
#+end_quote

*Sample questions*
- Tell me about a time when you solved a complex problem and how you
  went about doing it?
- How do you handle roadblocks or obstacles?
  
** 4. Are Right, A Lot

#+begin_quote
Leaders are right a lot. They have strong judgment and good
instincts. They seek diverse perspectives and work to disconfirm their
beliefs.
#+end_quote

*Sample questions*
- Tell me about a time when you have to make a decision without much
  customer data?
- Tell me about a time when had to convince team members on something
  that you proposed.
  
** 5. Learn and Be Curious

#+begin_quote
Leaders are never done learning and always seek to improve
themselves. They are curious about new possibilities and act to
explore them.
#+end_quote

*Sample questions*
- Tell me about a time when you built out a process? <-- I don't get this
- Tell me about a skill that you recently learned?
  
** 6. Hire and Develop the Best

#+begin_quote
Leaders raise the performance bar with every hire and promotion. They
recognize exceptional talent, and willingly move them throughout the
organization. Leaders develop leaders and take seriously their role in
coaching others. We work on behalf of our people to invent mechanisms
for development like Career Choice.
#+end_quote

*Sample questions*
- Tell me about a time when you had conflict with someone? How did you
  resolve it? What did you learn?
- Tell me about a time when you fired someone?
  
** 7. Insist on the Highest Standards

#+begin_quote
Leaders have relentlessly high standards — many people may think these
standards are unreasonably high. Leaders are continually raising the
bar and drive their teams to deliver high quality products, services,
and processes. Leaders ensure that defects do not get sent down the
line and that problems are fixed so they stay fixed.
#+end_quote

*Sample questions*
- Tell me about a time when you had to make a decision to make
  short-term sacrifices for long-term gians?
- Tell me about a time when you made decision based on data and you
  are ultimately wrong?
  
** 8. Think Big

#+begin_quote
Thinking small is a self-fulfilling prophecy. Leaders create and
communicate a bold direction that inspires results. They think
differently and look around corners for ways to serve customers.
#+end_quote

*Sample questions*
- Tell me about your greatest success?
- Tell me about a time when you are creative?
  
** 9. Bias for Action

#+begin_quote
Speed matters in business. Many decisions and actions are reversible
and do not need extensive study. We value calculated risk taking.
#+end_quote

*Sample questions*
- How have you convinced others to take action?
- How have you managed risk in a project?

** 10. Frugality

#+begin_quote
Accomplish more with less. Constraints breed resourcefulness,
self-sufficiency, and invention. There are no extra points for growing
headcount, budget size, or fixed expense.
#+end_quote

*Sample questions*
- Tell me about a time when you turned down more resources to complete a project?
- Tell me about a time when you had to accomplish big results with very little budget?
  
** 11. Earn Trust

#+begin_quote
Leaders listen attentively, speak candidly, and treat others
respectfully. They are vocally self-critical, even when doing so is
awkward or embarrassing. Leaders do not believe their or their team’s
body odor smells of perfume. They benchmark themselves and their teams
against the best.
#+end_quote

*Sample questions*
- Can you give me an example of how you manage conflict?
- How do you earn the trust of your team members?
  
** 12. Dive Deep

#+begin_quote
Leaders operate at all levels, stay connected to the details, audit
frequently, and are skeptical when metrics and anecdote differ. No
task is beneath them.
#+end_quote

*Sample questions*
- Tell me about the most complex project you worked on?
- Have you changed an opinion or direction using data?

** 13. Have Backbone; Disagree and Commit

#+begin_quote
Leaders are obligated to respectfully challenge decisions when they
disagree, even when doing so is uncomfortable or exhausting. Leaders
have conviction and are tenacious. They do not compromise for the sake
of social cohesion. Once a decision is determined, they commit wholly.
#+end_quote

*Sample questions*
- Tell me about a time when you had disagreement with your manager?
- How do you manage difficult conversations?

** 14. Deliver Results

#+begin_quote
Leaders focus on the key inputs for their business and deliver them
with the right quality and in a timely fashion. Despite setbacks, they
rise to the occasion and never settle.
#+end_quote

*Sample questions*
- Describe a challenging project you worked on and why is it challenging?
- How do you prioritize?
  
** 15. Strive to be Earth’s Best Employer

#+begin_quote
Leaders work every day to create a safer, more productive, higher
performing, more diverse, and more just work environment. They lead
with empathy, have fun at work, and make it easy for others to have
fun. Leaders ask themselves: Are my fellow employees growing? Are they
empowered? Are they ready for what’s next? Leaders have a vision for
and commitment to their employees’ personal success, whether that be
at Amazon or elsewhere.
#+end_quote

*Sample questions*
- Tell me about a time when you had to motivate a team after demoralizing events?
- Tell me about a time when an employee gave you negative feedback?

** 16. Success and Scale Bring Broad Responsibility

#+begin_quote
We started in a garage, but we’re not there anymore. We are big, we
impact the world, and we are far from perfect. We must be humble and
thoughtful about even the secondary effects of our actions. Our local
communities, planet, and future generations need us to be better every
day. We must begin each day with a determination to make better, do
better, and be better for our customers, our employees, our partners,
and the world at large. And we must end every day knowing we can do
even more tomorrow. Leaders create more than they consume and always
leave things better than how they found them.
#+end_quote

*Sample questions*
- Tell me about a time when you had problem and had to discover the real cause?
- Describe a time when your project failed?
