#+title:      dusty adventure
#+date:       [2025-08-28 Thu 05:03]
#+filetags:   
#+identifier: 20250828T050303

* What happened

** Day 1

Sravani and I went to Williams, Arizona for a weekend getaway, and of
course, we brought Dusty along. His wings weren’t clipped at the time,
so at home he would often hover and fly around the rooms freely,
always keeping us entertained.

When we got to our Airbnb, we decided to cook. I had a craving for
chile rellenos, so we picked up all the ingredients at the local
grocery store. Back in the kitchen, I made rice and beans while
roasting the peppers on the common grill outside. At one point, I
dashed back inside to quickly turn off the rice. Dusty, as playful as
ever, landed on my shoulder and I gently put him back on his cage
before heading back out.

But just as I was leaving—it happened. Dusty suddenly took off, flying
right past me.

It was about fifteen minutes before sunset. I watched him soar higher
and higher until he landed on a tall tree, maybe three or four houses
away. He called out two or three times, and then… silence. The sun
went down, and the night began.

That night, we couldn’t eat, we couldn’t sleep. We scoured websites
about how to capture lost birds, posted on social media, and hoped
against hope that we would find him.


** Day 2


The next morning we started searching at 5 a.m. We walked around
playing cockatiel flock calls. We did not hear anything back. We
almost gave up, and as a last resort, we drove around playing flock
calls in our car in a 2-mile radius.

We heard him call back. He sat on a tall tree almost a mile away from
our Airbnb. The location had old trailers. A kind gentleman saw us and
helped us. He gave us a ladder and asked permission for us to climb on
his neighbor’s trailer. We almost spent 2 hours there playing flock
calls, calling his name, and him calling back (this is wrong, as we
understood on the last day). After 2 hours of back and forth, Dusty
flew again and disappeared into other trees.

We tried searching immediately using flock calls, but we did not hear
anything. We took a break and went to Kadampa Meditation Center. We
saw this place the previous day when we went to Grand Canyon Deer
Farm. There we decided to eat something after the meditation class,
and there we met very nice people. One of them was Kit. She helped us
get in contact with the local animal rescue center, and we met Dusty
(same name as my bird!).

As per her advice, we made a missing poster and also posted on the
local Williams group. While distributing the posters that afternoon we
heard Dusty again. This time we set his cage down and played flock
music (again, not correct). He flew again, we chased after him, but he
never flew to the ground for us to pick him up. He disappeared.

That evening at dusk, we tried walking and driving with flock calls
again. We did not hear any response. We were about to give up, and
went to see Kelsey (Dusty introduced her, who lives near the
church). When we were talking to her, we saw Dusty fly past us. Two
sparrows were chasing him. We saw him fly across the railway track and
into the mountain with pine trees. We ran after him, hoping he would
come down. He did not. He stayed on the pine tree for 10 minutes and
again flew back towards the houses.

** Day 3

Early morning, Kit helped us by walking with us and whistling. When we
were about to give up, we again saw Dusty fly past us! That time we
decided to extend our stay by 5 more days and keep looking for
him. Until we did not hear his voice for a day, we wanted to keep
trying.

That afternoon, we found that we should not play flock music once we
found the bird. The best way to get him down is to set his cage near
the tree he flew into and wait for him to come back. We needed to
create a safe place for him to return. We also found that a second
method to get the bird back to the cage is to fix a spot and play
flock sounds from there. Birds will learn the location and look for a
safe spot to land.

That evening, we tried this. We got permission from Kelsey to use the
church parking lot and played flock calls. Almost at night, we heard
Dusty call back in a soft tone. We knew he was near the church.

** Day 4

That morning we tried the fixed spot method again, but we did not hear
any response.

In the afternoon, we decided to go back to Phoenix (a 3-hour drive),
feed our fish, and then return to Williams to keep looking for Dusty.

On our way back, we got a call saying they had seen Dusty on top of
their house chimney. We were so excited and wanted to be there
immediately. But alas, we were still 2 hours away and had to stop to
charge our electric car. That was the moment I decided our next car
would not be electric—they are not good in emergencies. We called them
back and asked them to bring Dusty’s cage, which was kept at the
church premises nearby. They did, and voilà! Dusty flew straight into
his cage and started eating!

The amazing thing about these people finding our bird is how it
happened. Their son had seen us leaving something at the church
premises and told his parents. The parents manage and own the church,
and when they checked, they saw our note on the cage. The wife
recognized that Dusty’s flock call was not from a wild bird. That
recognition saved him.

* What I learnt form this experience?

- Life is momentary. A few seconds can change everything, like dusty flying away.
- Attachment causes pain and suffering. Only god is everlasting, everything else is subject to chagne.
- Be kind and be grateful that you can make the world a little better. God has given you the opportunity to do his will, cherish it.
- Having a good community is important. They help us and guide us in our moment of need.
- I want to volunteer in a resque center.
- If I am this hurt for Dusty, the same compassion should be applied to all animals. I will avoid meat.
- I will use money for donation rather than my personal pleasure.
