#+title:      multiple linear regression
#+date:       [2026-02-11 Wed 08:17]
#+filetags:   
#+identifier: 20260211T081744

Let there be \( p \) predictors. We model the response, \( Y \), as 

\begin{equation}
Y = \beta_0 + \beta_1 X_1 + \beta_2 X_2 + \ldots + \beta_p X_p + \epsilon \tag{1}
\end{equation}

In an ideal scenario the predictors are uncorrelated. This allows us to
make causal statements like, a certain change in \(X_j\) will result in
a certain change in \(Y\).

But, in practice this is not the case and the predictors are correlated. This causes

- The variance of all the coefficients to increase, sometime dramatically.
- Interpretation becomes hazardous. When \(X_j\) changes, everything else changes.

Hence, the claims of causality should be avoided for observational data.

** Is at least one predictor useful?

We can determine this using *F-statistic*.

\begin{equation}
F = \frac{\frac{TSS - RSS}{P}} {\frac{RSS}{n - p - 1}}
\end{equation}

The $\frac{TSS - RSS}{P}$ captures drop in training error per predictor when compared
to no model ($y = \bar{y}$).

The $\frac{RSS}{n - p - 1}$ captures the residual per each degree of freedom.

** What are important predictors?

For a small number of predictors, $P$, it is easy to compute performance of models
using all the possible subset of predictors. But, as $P$ grows the number of possible
models grow exponentially, with $2^P$.

A smart way of doing this is using *Forward selection* and *Backward
selection*.

*** Forward selection:

1. Begin with the **null model** (\(M_0: y = \bar{y}\)), which
   contains no predictors.

2. In step 1, fit all \(p\) simple regressions (\(y = \beta_0 +
   \beta_j x_j\)) and select the predictor that provides the
   greatest improvement in fit, indicated by the largest reduction
   in Residual Sum of Squares (RSS).

3. In step \(k\) (where \(k \geq 2\)), based on the current model,
   evaluate each remaining predictor one at a time and choose the one
   that yields the most significant improvement in fit.

4. Update the model by incorporating this new predictor and
   continue to step 3.

5. Terminate the process when no remaining predictor offers a
   meaningful enhancement.

*** Backward selection:

1. Begin with the full model: 

\begin{equation}
M_p: y = \beta_0 + \beta_1 x_1 + \beta_2 x_2 + \ldots + \beta_p x_p.
\end{equation}

2. In step 1, fit all models generated by removing one predictor from
   the current model, and select the model that exhibits the smallest
   loss of fit, indicated by the least increase in residual sum of
   squares (RSS).

3. At step $k \leq p-1$, from the current model, evaluate the impact
   of removing each remaining predictor one at a time, and eliminate
   the one whose removal leads to the least deterioration in fit.

4. Update the model by excluding this predictor and repeat step 3.

5. Terminate the process when the removal of any remaining predictor
   significantly degrades the model or when a specified criterion
   (such as AIC, BIC, adjusted $R^2$, or cross-validation error) is
   optimized.
