#+title:      verse 34 35  36
#+date:       [2024-05-24 Fri 06:31]
#+filetags:
#+identifier: 20240524T063153
#+filetags:   :gita:
#+OPTIONS: \n:t
#+HUGO_SECTION: gita
#+HUGO_BASE_DIR: ~/Dropbox/notes/hugo-notes/


* Verse

अकीर्तिं चापि भूतानि कथयिष्यन्ति तेऽव्ययाम् |
सम्भावितस्य चाकीर्ति र्मरणादतिरिच्यते || 34||

भयाद्रणादुपरतं मंस्यन्ते त्वां महारथा: |
येषां च त्वं बहुमतो भूत्वा यास्यसि लाघवम् || 35||

अवाच्यवादांश्च बहून्वदिष्यन्ति तवाहिता: |
निन्दन्तस्तव सामर्थ्यं ततो दु:खतरं नु किम् || 36||

* Short translation

People, too, will recount thy everlasting infamy ; and, to one who has
been esteemed, infamy is more than death.

The great car-warriors will think thou hast withdrawn from the battle
through fear ; and, having been (hitherto) highly esteemed by them,
thou wilt incur their contempt.

Thy enemies, too, scorning thy power, will take many abusive
words. What is more painful than that?

* My notes

Here Krishna is appealing to to Arjuna esteem. He is known as a very
proficient warrior and held in high regards. By not fighting the war,
he will lose this credibility.

Krishna is using common sense here. It will feel really bad when
people who you respect and adore does not respect you.
