#+title:      verse 40
#+date:       [2024-05-27 Mon 07:09]
#+identifier: 20240527T070949
#+filetags:   :chapter2:gita:
#+OPTIONS: \n:t
#+HUGO_SECTION: gita
#+HUGO_BASE_DIR: ~/Dropbox/notes/hugo-notes/


* Verse

नेहाभिक्रमनाशोऽस्ति प्रत्यवायो न विद्यते |
स्वल्पमप्यस्य धर्मस्य त्रायते महतो भयात् || 40||

* Short translation

There is no loss of effort here, there is no
harm. Even a little of this devotion delivers one
from great fear

* My notes

Doing work as prescribed in Karma Yoga will have,

- *No loss of effort:* When working for the world, we have to
  complete the task to see the result. In contrast, we do Karma Yoga
  to purify our mind so that it can meditate and be calm. This does
  not require the task to be done. Hence, no effort is wasted.


- *There is no harm:* Worldly tasks can cause harm to us. For
  example, cooking a dish for family can get negative review. This
  can bother us and escalate into unnecessary arguments. But, doing
  the same cooking as Karma Yoga, we are detached fromt he
  feedback. It will not bother us.


- *Delivering from fear:* When we start a task we are focused on
  resutls. It builds anxiety in us and keeps us on toes to make it
  successful. The bigger the project the more the anxiety. But, doing
  work as Karma Yoga, we do not care for the resutl but the work
  itself. A kind of peace dawns on us when we are not attached to the
  results.
