#+title:      verse 45 46 47
#+date:       [2024-08-26 Mon 09:10]
#+filetags:   :chapter2:class16:gita:
#+identifier: 20240826T091004
#+OPTIONS: \n:t
#+HUGO_SECTION: gita
#+HUGO_BASE_DIR: ~/Dropbox/notes/hugo-notes/

* Verses

त्रैगुण्यविषया वेदा निस्त्रैगुण्यो भवार्जुन |
निर्द्वन्द्वो नित्यसत्त्वस्थो निर्योगक्षेम आत्मवान् || 45||

यावानर्थ उदपाने सर्वत: सम्प्लुतोदके |
तावान्सर्वेषु वेदेषु ब्राह्मणस्य विजानत: || 46||

कर्मण्येवाधिकारस्ते मा फलेषु कदाचन |
मा कर्मफलहेतुर्भूर्मा ते सङ्गोऽस्त्वकर्मणि || 47 ||

* Short translation

*Verse 45*

The Vedas treat of the triad of the gunas. Be, O Arjuna, free from the
triad of the gunas, free from pairs (dualities), free from acquisition
and preservation, ever remaining in the Sattva (Goodness), and
self-possessed.

*Verse 46*

What utility there is in a reservoir by the side of an all-spreading
flood of water. the same (utility) there is in all Vedas for an
enlightened Brahmatta.

*Verse 47*

Thy concern is with action alone, never with results. Let not the
fruit of action be thy motive, nor let thy attachment be for inaction.

* My notes

** Verse 45

The vedas can be partitioned into karma kanda and jnana kanda. Karma
kanda talks about fulfilling our desires in this world and the
next. They prescribe rituals and moral way of getting material
(composed of three gunas) happiness. Krishna knows that material
happiness is momentary, and recommenda Arjuna to go beyond.

His recommends Arjuna to go beyond by

1. Forbearing the dualities <- What life throws at you.

   To treat the dualities of life as same. Be calm at all times. The
   world will throw good and bad at you, do not be too happy nor too
   unhappy (it tooo will pass).

2. Always practicing patience (positive psycology: resilience)

3. Letting go of aquisition and preserving material things.

4. Being established in higher reality of your choosing.

   Higher in the sense, the reality that you belive goes beyond the
   three gunas. It can be choosen diety, it can be knowlege of self,
   selfless living, etc.

** Verse 46

All the advice on worldly happiness is like small reservoirs of
water. The happiness/contentment of realizing the true self is like
flooded river. What is the use of small reserviours when you have
a river full of water?!

** Verse 47

Action and inaction originates from desire. In the lower spectrum of
things there is inaction, which originates from laziness
(tamas). There is action due to self centered desires (rajas) and
action due to unselfish motives (sattva).

There is yet another way to action that is beyond these. Sattva action
is good, it gives peace and calmness, but still there is small part of
our little self invested invested in it. The goal is disinterested
action, different form uninterested action. It work should be done
with care and yet the results shold not be the motivate.

In the context of free will, humans have free will in doing the
action, but they do not have control on the results. It is also
important to note that this quality is unique to humans, animals
are instinctive creatures.

I feel all the different Yoga make our smaller self more and more
divine and untimately makes us realize that we are that.<-- Not sure
if this is correct.
